version: 2

models:
  - name: denormalized_data
    description: "A denormalized table combining Users, Artists, Songs, ListeningHistory, and UserPreferences"
    columns:
      - name: user_id
        description: "The primary key for the Users table"
        tests:
          - unique
          - not_null
      - name: Artist_id
        description: "The primary key for the Artists table"
        tests:
          - unique
          - not_null
      - name: song_id
        description: "The primary key for the Songs table"
        tests:
          - unique
          - not_null
      - name: history_id
        description: "The primary key for the ListeningHistory table"
        tests:
          - unique
          - not_null
      - name: preference_id
        description: "The primary key for the UserPreferences table"
        tests:
          - unique
          - not_null
