name: 'wu3project'
version: '1.0.0'
config-version: 2

profile: 'wu3project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  wu3project:
    example:
      +materialized: view
    denormalized_data:
      +materialized: view
